server:
  port: 88
spring:
  jackson:
    serialization: { WRITE_DATES_AS_TIMESTAMPS: true }
  datasource:
    url: jdbc:mysql://mysql:3326/test_db?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: rootmima





logging:
  level:
    cn.zooways.app.mapper: debug